apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM= # base64 encoded value of 'mydatabase'
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded value of 'myuser'
  POSTGRES_PASSWORD: WDFnMHleTTEzS0ZASjQz # base64 encoded value of 'mypassword'
