apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
