apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  DATABASE_NAME: cG9zdGdyZXM=
  AUTH_DATABASE_NAME: YXV0aF9kYg==
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: WDFnMHleTTEzS0ZASjQz
  DATABASE_HOST: cG9zdGdyZXM=
